name: minmo_study

channels:
  - defaults
  - anaconda
  - pip
dependencies:
  - python=3.13.1
  - pip=24.2
  - scipy=1.14.1
  - pandas=2.2.3
  - statsmodels=0.14.4
  - pip:
    - nibabel==5.3.2
    - matplotlib==3.7.3
    - pingouin==0.5.5